# Module 03 - Scientific Computing with Numpy

---

#### <a href="linkedin.com/in/tasmim-rahman-adib-403074221">Tasmim Rahman Adib</a>
![numpylogo](../img/numpy.jpeg)

# Lecture 3.2 - Indexing, Slicing, Subsetting
## Agenda
- Indexing
- Slicing
- Subsetting

In [1]:
#conventional import
import numpy as np

## 3.2.1 Indexing
![indexing](../img/axis.jpg)

### Positive Indexing
Select `nth` element of an array by using `var[position]`

In [3]:
# Create an array 
A = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(A)

[1 2 3 4 5 6 7 8]


In [6]:
# Select 0th element of `A`
print(A[0])

1


In [7]:
# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Indexing a single element (row 1, column 2)
print(arr[1, 2])

6


### Negative Indexing

In [9]:
# Select last element of `A`
print(A[-1])

8


In [11]:
print(A[-2])

7


Extract a Portion of a Sequence by specifying a lower and upper bound. The lower bound element is `included`, but the upper-bound element is `not included`. Mathematically: [lower, upper]. The stop value specifies the stride between elements.


In [2]:
B = np.array([1, 2, 3, 4, 5, 6, 7])

In [3]:
B

array([1, 2, 3, 4, 5, 6, 7])

In [4]:
# indices: A[i:j] => i: j-1 
B[1:3]

array([2, 3])

In [5]:
# negative indices work also
B[1:-2]

array([2, 3, 4, 5])

In [6]:
B[-4:3]

array([], dtype=int64)

Omitted boundaries are assumed to be the beginning (or end) of the list

In [8]:
# grab first theree elements: first n elements A[: n]
B[:3]

array([1, 2, 3])

In [9]:
B[3:]

array([4, 5, 6, 7])

In [10]:
# grab last two elements 
B[-2:]

array([6, 7])

In [11]:
# grab every other elements 
B[::2]

array([1, 3, 5, 7])

## 3.2.2 Slicing
Slicing allows accessing a range of elements in an array. You can specify the start, stop, and step.
![numpy_slicing](../img/slicing.png)

## 1D Array Slicing
- 1D array at index `i`
- Returns the `ith` element of an array
- **Syntax:** `array[i]`

In [12]:
# Create an 1D arary 
A1 = np.array([11, 22, 34, 12, 15])

In [13]:
# Select ith element of A1 
A1[1]

np.int64(22)

In [14]:
# Negative indexing 
A1[-1]

np.int64(15)

## 2D Array Slicing
- 2D array at index `[i][j]`
- Returns the `[i][j]` element of an array
- **Syntax:** `array[i][j]`

In [15]:
# Create an 2D array 
A2 = np.array([[0, 1, 3], [4, 6, 7]])

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.


In [16]:
# Select the first row of A2 
A2[0]

array([0, 1, 3])

In [17]:
# Select the first element of first row 
A2[0][0]

np.int64(0)

__Note__

- First, `A2[0]` = [0, 1, 3], which is the first row of array `A2`
- Second, `A2[0]` select the first element of first row. 

In [18]:
# Select the second row of A2 
A2[1]

array([4, 6, 7])

In [19]:
# Select the 3rd element of second row 
A2[1][2]

np.int64(7)

## 3.2.3 Subsetting
Subsetting is like indexing but usually refers to selecting elements from an array based on a condition.

In [21]:
# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [22]:
# Subsetting elements greater than 5
subset_arr = arr[arr > 5]  # Output: array([6, 7, 8, 9])
print(subset_arr)


[6 7 8 9]


*Copyright &copy; 2024  [Md. Jubayer Hossain](https://hossainlab.github.io/) &  [Center for Bioinformatics Learning Advancement and Systematic Training (cBLAST)](https://www.cblast.du.ac.bd/). All rights reserved*