# Module 03 - Scientific Computing with Numpy

---

#### <a href="linkedin.com/in/tasmim-rahman-adib-403074221">Tasmim Rahman Adib</a>
![numpylogo](../img/numpy.jpeg)

# Lecture 3.6 - Linear Algebra Operations
## Agenda
- Determinant of Matrix
- Rank of Matrix
- Inverse of Matrix

In [1]:
# import numpy
import numpy as np 

### 3.6.1 Determinant of matrix 
- The determinant of a matrix is a special number that can be calculated from a **square matrix**
\begin{equation}
A = \begin{bmatrix} a & b \\ c & d \end{bmatrix} \\ 
det(A) = ad - bc 
\end{equation}
Whre, A is a $2 \times 2$ matrix. 

- `np.linalg.det()` - performs determinant of the matrix 
- **Syntax:** `np.linalg.det(matrix)`

In [2]:
# create matrix A
A = np.matrix("4, 5, 16, 7; 2,-3,2,3; 3,4,5,6; 4,7,8,9")
print(A)

[[ 4  5 16  7]
 [ 2 -3  2  3]
 [ 3  4  5  6]
 [ 4  7  8  9]]


In [3]:
# create matrix B
B = np.matrix("4,5,6,7;2,-3,3,3; 3,4,5,6; 4, 7,8,9")
print(B)

[[ 4  5  6  7]
 [ 2 -3  3  3]
 [ 3  4  5  6]
 [ 4  7  8  9]]


In [4]:
# determinant of A 
np.linalg.det(A) 

np.float64(128.00000000000009)

In [5]:
# determinant of B 
np.linalg.det(B)

np.float64(12.000000000000032)

### 3.6.2 Rank of matrix 
- You can think of an $r x c$ matrix as a set of r row vectors, each having c elements; or you can think of it as a set of c column vectors, each having r elements.
- The rank of a matrix is defined as (a) the maximum number of linearly independent column vectors in the matrix or (b) the maximum number of linearly independent row vectors in the matrix. Both definitions are equivalent.
- If r is less than c, then the maximum rank of the matrix is r.
- If r is greater than c, then the maximum rank of the matrix is c.
- `np.linalg.matrix_rank()` - returns rank of the matrix 
- **Syntax:** `np.linalg.matrix_rank(matrix)`

In [6]:
A.shape 

(4, 4)

In [7]:
# rank of matrix A 
np.linalg.matrix_rank(A)

np.int64(4)

In [8]:
# rank of matrix B 
np.linalg.matrix_rank(B)

np.int64(4)

### 3.6.3 Inverse of a Matrix 
- `np.linalg.inv()` - returns the multiplicative inverse of a matrix.
- **Syntax:** `np.linalg.inv(matrix)`

In [9]:
# inverse of matrix A 
np.linalg.inv(A)

matrix([[ 9.37500000e-02, -4.68750000e-01,  3.68750000e+00,
         -2.37500000e+00],
        [ 1.00929366e-16, -2.50000000e-01,  5.00000000e-01,
         -2.50000000e-01],
        [ 9.37500000e-02,  3.12500000e-02, -3.12500000e-01,
          1.25000000e-01],
        [-1.25000000e-01,  3.75000000e-01, -1.75000000e+00,
          1.25000000e+00]])

In [10]:
# inverse of matrix B 
np.linalg.inv(B)

matrix([[ 1.50000000e+00, -8.32667268e-17, -1.00000000e+00,
         -5.00000000e-01],
        [ 2.50000000e-01, -1.66666667e-01, -3.33333333e-01,
          8.33333333e-02],
        [ 1.00000000e+00,  3.33333333e-01, -3.33333333e+00,
          1.33333333e+00],
        [-1.75000000e+00, -1.66666667e-01,  3.66666667e+00,
         -9.16666667e-01]])

*Copyright &copy; 2024  [Md. Jubayer Hossain](https://hossainlab.github.io/) &  [Center for Bioinformatics Learning Advancement and Systematic Training (cBLAST)](https://www.cblast.du.ac.bd/). All rights reserved*